swagger: '2.0'
info:
  title: Bank Transactions API documentation
  description: Contains all available API endpoints for bank transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - Transactions
      summary: Get all transactions for the current month
      description: API for retrieving all transactions for the current month
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '500':
          description: Internal Server Error
    post:
      tags:
        - Transactions
      summary: Add a new transaction
      description: API for adding a new transaction
      parameters:
        - in: body
          name: body
          description: Transaction payload
          required: true
          schema:
            $ref: '#/definitions/TransactionInput'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction created successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid fields
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Get transaction details
      description: API for retrieving the details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transactions
      summary: Update transaction details
      description: API for updating the details of a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Transaction payload
          required: true
          schema:
            $ref: '#/definitions/TransactionInput'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Transactions
      summary: Delete a transaction
      description: API for deleting a specific transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to delete
          required: true
          type: string
      produces:
        - application/json
      responses:
        '204':
          description: Transaction deleted successfully
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date-time
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
  TransactionInput:
    type: object
    properties:
      date:
        type: string
        format: date-time
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
    required:
      - date
      - description
      - amount
